### ISSUE TITLE
How about Ubuntu 16

### ISSUE THREAD

**Issue by wine3603** [stephane-caron/lipm_walking_controller#1]
Heyyyyy, man,
This work is so coooooool ! :+1: 
Will you move it to Ubuntu 16 and a newer ROS release?
BTW there is a typo in the fourth ref in your HAL pre-print. ::

**Comment by stephane-caron** [comment]
This is confirmed (and the README updated), as we have been running this controller on both Ubuntu 14.04 and 16.04 since January.
