### ISSUE TITLE
Calculating force from ZMP

### ISSUE THREAD

**Issue by wyqsnddd** [stephane-caron/lipm_walking_controller#13]
In eq. (9) of the paper [Stair Climbing Stabilization of the HRP-4 Humanoid Robot
using Whole-body Admittance Control](https://hal.archives-ouvertes.fr/hal-01875387/document), we obtained force from ZMP. 

Is it a straight forward result by injecting `zmp` to eq. (2)?

**Comment by stephane-caron** [comment]
Basically yes, you get it as follows:

- Start from eq. (1)
- Force: replace the CoM acceleration by eq. (3)
- Moment: the rate of change of the angular momentum around the CoM is zero because we are in the inverted pendulum mode

This gets you to eq. (9).
