### ISSUE TITLE
Deriving commanded ZMP from DCM feedback

### ISSUE THREAD

**Issue by wyqsnddd** [stephane-caron/lipm_walking_controller#14]
The equation above eq. (9) of the paper [Stair Climbing Stabilization of the HRP-4 Humanoid Robot using Whole-body Admittance Control](https://hal.archives-ouvertes.fr/hal-01875387/document) looks a bit confusing. 

We need to assume that `\xi - \xi^* = \xi^m - \xi^*` to derive the equation, see details in the figure: 
![IMG_20191008_093449](https://user-images.githubusercontent.com/6009684/66397839-f4c2e100-e9dc-11e9-9de8-c9a06bf81fb1.jpg)

**Comment by stephane-caron** [comment]
That's right, basically in feedback control you assume that your state estimate is correct. Here the state is the DCM, so this assumption amounts to `\xi = \xi^m`.

In practice, state estimation errors are reflected into feedback errors. That's one reason why we have for instance steady-state errors. We add the integral term to compensate them as proposed in [Balance control based on Capture Point error compensation for biped walking on uneven terrain](https://doi.org/10.1109/HUMANOIDS.2012.6651601).
