### ISSUE TITLE
Sample Projects for V-REP

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/lipm_walking_controller#17]
Hi Dr.Caron

I am currently trying to import our robot into v-rep software. There was some sample projects for choreonoid in "mc_openrtm" package such as HRP4Comanoid which I got information about how to make a package for our robot. Do you have any similar sample projects for V-REP? So I could use those and make necessary files for my robot based on them.

Thank You

**Comment by stephane-caron** [comment]
Hi @mohamadmahdavian. There are no environment-specific (e.g. real-robot, Choreonoid or V-REP) project files on the controller side. You will find such files in the related projects [mc_openrtm](https://gite.lirmm.fr/multi-contact/mc_openrtm) for Choreonoid and [vrep-api-wrapper](https://gite.lirmm.fr/vrep-utils/vrep-api-wrapper) for V-REP.

As far as I understand, the main thing you need to do for V-REP is to import the ``vrep_api_wrapper_utils.ttm`` module into your scene and edit the child script of your robot scene object accordingly. Feel free to ask your questions in the issue tracker of this project for details.
