### ISSUE TITLE
Terminal Constraints for Walking Pattern Generation

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#19]
Dear Dr. Caron,

I have encountered an issue with the walking pattern generation for which I appreciate your help. I don’t understand why we should considerer ZMP and DCM terminal constraints at the end of each predictive horizon? My understanding from these constraints is the bipedal robot will end up in a stationary position at the end of the predictive horizon. If my understanding is correct I think both terminal constraints should only be applied at the end of the walking.

**Comment by stephane-caron** [comment]
The ZMP and DCM constraints at the end of the predictive horizon are a viability condition that guarantees _recursive feasibility_ of the MPC. Check out [Ciocca et al. (2017)](https://hal.inria.fr/hal-01618881) for details on this.

In practice, the robot does not reach this stationary state while walking as new steps keep being added and predictive trajectories are recomputed accordingly.
