### ISSUE TITLE
IK Tasks

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#27]
Dear Dr. Caron,
I have encountered an issue with the IK for which I appreciate your help. As you said in your paper, IK is solved based on six tasks:

1- Maintain foot contact(s)
2- CoM position and velocity tracking
3- Swing foot position and velocity tracking
4- Bend the chest to a prescribed angle
5- Keep the pelvis upright
6- Regularizing half-sitting joint configuration

I know that the IK is in the acceleration level. However, I cannot find a damping coefficient for some tasks. Would you please explain it? 
The first task  "Maintain foot contact(s)" means keep support foot in contact with the ground and is a PD regulation. In the codes, `mc_tasks::coptask` is used to define the first and third tasks. Why don't you use a `PositionTask` instead of `COPTask`? What does `mc_tasks::coptask` do?

**Comment by stephane-caron** [comment]
> However, I cannot find a damping coefficient for some tasks. Would you please explain it?

What tasks cannot you find a damping coefficient for?

> Why don't you use a PositionTask instead of COPTask? 

The CoPTask implements foot damping control, which is described [in Section III.A of the paper](https://hal.archives-ouvertes.fr/hal-01875387/document). If we used a position task here, we wouldn't get the force control we need for balance. Here is an overall picture of what balance control is:

![stabilization](https://user-images.githubusercontent.com/1189580/68351362-98232500-0146-11ea-973d-3b7157677178.png)

In the stabilizer, force control is implemented by the CoPTasks, ``updateFootForceDifferenceControl()`` and ``updateCoMTaskZMPCC()`` functions. They correspond to the three admittance control strategies described in the paper and summarized at the bottom of this [overview poster](https://scaron.info/files/icra-2019/poster.pdf).

> What does mc_tasks::coptask do?

Take a look at the documentation comments in ``CoPTask.h``, as well as in the header file of its parent classes. Feel free to ask further questions if anything is not explained or badly explained there.
