### ISSUE TITLE
Wrench distribution QP computation times

### ISSUE THREAD

**Issue by stephane-caron** [stephane-caron/lipm_walking_controller#30]
We've been comparing the performance of LSSOL with QuadProg in the ``topic/NoLSSOL`` branch for the wrench distribution quadratic program (WDQP) of the stabilizer. Currently QuadProg solves it much faster:

![image](https://user-images.githubusercontent.com/1189580/69221895-ab5cd880-0bbb-11ea-91b2-3c6656904a1a.png)

On average QuadProg runs around 0.02 ms, vers 025 ms for LSSOL.

**Comment by stephane-caron** [comment]
There is a short walking phase (``warmup`` plan) in the plot above, but it is not so clear. Here is a walking plan (``forward_30cm_steps``):

![image](https://user-images.githubusercontent.com/1189580/69240701-61d2b480-0be0-11ea-81c6-6d54e9e53b2e.png)

The difference between DSP and SSP problem solving times is quite clear.

**Comment by stephane-caron** [comment]
@aescande Computation times are the same with and without custom QR decomposition for QuadProg:

![image](https://user-images.githubusercontent.com/1189580/69242145-93994a80-0be3-11ea-9c74-6bddaab554e7.png)

At the last DSP of this example, the "no QR" (_i.e._ ``Q = A.transpose() * A``) solution is roughly 2x closer (than the "QR" one) to the one found by LSSOL:

![image](https://user-images.githubusercontent.com/1189580/69242348-09051b00-0be4-11ea-8f27-3f8a1942c5a8.png)

**Comment by aescande** [comment]
In the comparison QuadProgQR vs QuadProdNoQR, are you measuring the time spent to form Q for the NoQR case ?

How come that the earlier timing you did between the controllers based on LSSOL and QuadProgNoQR were very close ?

**Comment by stephane-caron** [comment]
> In the comparison QuadProgQR vs QuadProdNoQR, are you measuring the time spent to form Q for the NoQR case ?

Yes, you can check the instructions between ``startTime`` and ``endTime`` in both case the [QR](https://github.com/stephane-caron/lipm_walking_controller/blob/262d4dc76a65860af9d5f8d246433bb2ccea1e46/src/Stabilizer.cpp#L838) and [NoQR](https://github.com/stephane-caron/lipm_walking_controller/blob/262d4dc76a65860af9d5f8d246433bb2ccea1e46/src/Stabilizer.cpp#L830) cases. Actually, the NoQR case has a slight disadvantage here as it also includes the computation of ``c = -A^T b`` :wink: 

> How come that the earlier timing you did between the controllers based on LSSOL and QuadProgNoQR were very close ?

I didn't commit this intermediate version so I can't tell you for sure. In the commit history timings start after we switched to the QR decomposition.

**Comment by stephane-caron** [comment]
> Actually, the NoQR case has a slight disadvantage here as it also includes the computation of c = -A^T b

Removing this bias the NoQR version is actually faster:

![image](https://user-images.githubusercontent.com/1189580/69293063-17d2e880-0c4b-11ea-9f2f-5314954066fb.png)

**Comment by stephane-caron** [comment]
We investigated the performance of LSSOL deeper with @aescande, using settings from [Tasks](https://github.com/jrl-umi3218/Tasks/) to improve its solve times, notably:
```c++
  lssol_.warm(true);
  lssol_.persistance(true);
  lssol_.forceMinSize(false);
```
This brought the number of iterations from 10-40 to 1-4, so that the average solve time drops from 200-400 µs to 50 µs. Incidentally, these are roughly the same solve times than Tasks' IK. Still, much slower than QuadProg:

![image](https://user-images.githubusercontent.com/1189580/69304765-334aed00-0c65-11ea-8858-1bdd0b81ccf6.png)

Roughly, QuadProg is 6x faster than LSSOL on the double-support QP and 20x faster on the single-support QP.
