### ISSUE TITLE
Building against mc_rtc 1.0

### ISSUE THREAD

**Issue by arntanguy** [stephane-caron/lipm_walking_controller#35]
You should probably consider building against the upcoming `v1.0` release of `mc_rtc` ;)
Very minor changes, basically the only thing to do is replace `GUIState.h` by `<mc_rtc/gui.h>` (and bump your required commit references in your documentation).

I've just merged your `v1.6` release, and made these changes, along with removing the unnecessary ros dependencies in https://github.com/jrl-umi3218/lipm_walking_controller.

Feel free to merge these changes to your own repo if you are fine with a `catkin_free` build. This may require some minor changes to your docker file.

**Comment by stephane-caron** [comment]
Sure, let's keep this issue open until mc_rtc 1.0's official release (as a :gift: under the Christmas tree tomorrow? :smile: :santa:)

**Comment by stephane-caron** [comment]
Closing this issue now. This repo is for the archival version of the controller, that is, the one that matches the [Docker image](https://hub.docker.com/r/stephanecaron/lipm_walking_controller). Developers who want to install from source and use an up-to-date version of mc_rtc should go for the maintained fork at https://github.com/jrl-umi3218/lipm_walking_controller :wink:
