### ISSUE TITLE
Force sensor selection

### ISSUE THREAD

**Issue by Ahmadreza-Shahrokhshahi** [stephane-caron/lipm_walking_controller#40]
Hi Dr. Caron,

I hope you're doing well.
As a part of the design of our exoskeleton robot, for selecting the force sensors, we need to make sure if measuring the horizontal components of the GRF (i.e. fx and fy) is needed. We have looked at the [paper](https://hal.archives-ouvertes.fr/hal-01875387/document) and the codes of the controller and the observer, but didn't find any equation in which using the horizontal components of the GRF is essential. Do you agree with me that having four one-axis force sensors for each footplate would be sufficient?
It is important for the sensor selection and would effect our costs and deign process.

Thank you

**Comment by stephane-caron** [comment]
Six-axis F/T sensor information (including horizontal GRF components) are used in the ``NetWrenchObserver`` to compute the net wrench of contact forces applied to the robot. Eventually however, only three components are consumed by the stabilizer:

- ZMP horizontal coordinates, used to compute
  - the D term in ``computeDesiredWrench()``
  - CoM admittance feedback in ``updateCoMTaskZMPCC()``
 (this is not a critical component, leave it disabled for starters)
- Force vertical coordinates used, in ``updateFootForceDifferenceControl()``

So, yes: you can shortcut the net wrench observer and provide these values directly to the stabilizer. This will work if you have four one-axis force sensors at your soles (this design has been _e.g._ tried on the Nao humanoid).
