### ISSUE TITLE
Standing Phase

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#41]
Dear Dr. Caron,

I have two questions:
1- How can I change the time duration of the Standing state?
2- I should record the state of walking during the time. How can I log the status of FSM?  

Thanks

**Comment by stephane-caron** [comment]
Hi @Saeed-Mansouri 

1. Standing is a state of the FSM. You can transition to it from the initial state by clicking on [Start standing](https://github.com/stephane-caron/lipm_walking_controller/wiki/Graphical-user-interface) in the GUI. The controller will stay in the Standing state until you click on ``Start walking``; there is no pre-defined duration.

2. You can check the ``walking_phase`` variable in your controller logs:

![2020-02-16-210122_1920x1200_scrot](https://user-images.githubusercontent.com/1189580/74611781-8c5cdc80-50ff-11ea-825c-798ceff0c22f.png)

It corresponds to the FSM state:

- -2 is Initial
- 3 is Standing
- 2 is DoubleSupport
- 1 is SingleSupport
