### ISSUE TITLE
CoMTask

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#42]
Hi Dr. Caron,

I added a new `PositionTask` to control pelvis position in the z-direction to have more natural walking. Also, I changed `dimweight` of CoMTask to `{0.5, 1., 0.}` and `{0., 0., 1.}` was set for the new `PositionTask`. However, I found that the third array of "com" element in the CoMTask of gui didn't change at all. I tried to find that what value returned for "com" element.

```
void CoMTask::addToGUI(mc_rtc::gui::StateBuilder & gui)
{
  TrajectoryTaskGeneric<tasks::qp::CoMTask>::addToGUI(gui);
  gui.addElement({"Tasks", name_},
                 mc_rtc::gui::Point3D("com_target", [this]() { return this->com(); },
                                      [this](const Eigen::Vector3d & com) { this->com(com); }),
                 mc_rtc::gui::Point3D("com", [this]() { return (this->com() - this->eval()).eval(); }));
}
```
As you can see below, it seems that `this->eval()` returns a cross-product of the com error and `dimweight`. However, I couldn't understand the physical interpretation of this process. I will appreciate it if you could explain it.

```
template<typename T>
Eigen::VectorXd TrajectoryTaskGeneric<T>::eval() const
{
  if(selectorT_)
  {
    return selectorT_->eval().cwiseProduct(trajectoryT_->dimWeight());
  }
  return errorT->eval().cwiseProduct(trajectoryT_->dimWeight());
}
```

**Comment by stephane-caron** [comment]
This question is related to mc_rtc. Continuing the discussion in the [mc_rtc issue tracker](https://github.com/stephane-caron/lipm_walking_controller/issues/42).
