### ISSUE TITLE
Getting all joints position and orientation

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/lipm_walking_controller#43]
Hi Dr.Caron

I need to get all joints position and orientations in LIPM package while robot is walking, possibly in Controller.cpp code. For example the knee joint position or ankle joint orientation. What is the simplest possible way, without using joint angles and solving Forward Kinematic. Is there any line of code for that in Controler.cpp code?

Thank You

**Comment by stephane-caron** [comment]
This question is related to mc_rtc, answering it in the proper issue tracker.
