### ISSUE TITLE
Foot force difference control 

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#50]
Hi Dr. Caron,

In the LIPM package, you added a term called `dfzDamping_` in the foot force difference control that is not mentioned in your article. I want to know what the effect of this damping term on the walking motion is? Which problems would happen if this term be ignored?

**Comment by stephane-caron** [comment]
As described in the *Admittance control* table of the [stabilizer tuning guide](https://scaron.info/doc/lipm_walking_controller/stabilizer.html), this parameter can be used to damp potential oscillations in double support. This damping can be used for [vertical vibration suppression on HRP-4](https://staff.aist.go.jp/k.kaneko/publications/2013_publications/ICRA2013-0371.pdf), however it is not indispensable and we left it to zero in our experiments with this robot.

Thank you for your question, I added this clarification to the doc.

> I want to know what the effect of this damping term on the walking motion is?

No significant effect on walking. It only applies if you get vibrations while standing in double support.

> Which problems would happen if this term be ignored?

You can ignore this parameter. If you do so and get standing vibrations, it then means that you should reduce your ``DFz`` admittance.

If you don't ignore this parameter, an alternative is to keep a high ``DFz`` and damp oscillations with it. But we didn't need that with either HRP-4 nor HRP-2Kai.
