### ISSUE TITLE
tuning the stabilizer

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#51]
Hi Dr. Caron,

I have found that something might be wrong in the below sentence that you stated in the Standing section of [tuning the stabilizer guideline](https://scaron.info/doc/lipm_walking_controller/stabilizer.html).

`On the left-hand plot, DCM proportional and integral gains were set to P=1 and I=10, and we see that the DCM is overdamped. On the right-hand plot, gains were set to P=2 and I=5, yielding a better performance (the DCM is only slightly underdamped).`

**Comment by stephane-caron** [comment]
Nice catch :ok_hand: it should be "underdamped" indeed. It's corrected now.
