### ISSUE TITLE
Making it obvious that jrl-umi3218 is the maintained version

### ISSUE THREAD

**Issue by arntanguy** [stephane-caron/lipm_walking_controller#53]
Hi @stephane-caron ,

I hope everything is going well for you :)

Would you mind updating the readme to make it more obvious that [jrl-umi3218/lipm_walking_controller](https://github.com/jrl-umi3218/lipm_walking_controller) is the maintained version, and that this repository is only an archival version. If you could also encourage people to install from our packages instead of building everything from source, that'd be quite helpful to help prevent issues (and make it much easier for us to debug problems). 

You're already mentioning it, but it's kinda hidden. The main issue is that it seems that most people endeavor to compile everything from source  including choreonoid and its dependencies (probably because they ended up on your repository first), and ultimately end-up running into issues somewhere along the line (we both know how messy it is to get choreonoid working properly that way).

I suggest something along the line of

> ## LIPM Walking Controller (archival version)
> Original code of the walking and stair climbing controller used in the experiments of [Stair Climbing Stabilization of the HRP-4 Humanoid Robot using Whole-body Admittance Control](https://hal.archives-ouvertes.fr/hal-01875387/document), as well as in an industrial demonstrator at the [Airbus Saint-Nazaire factory](https://cordis.europa.eu/project/rcn/194280/brief/en?WT.mc_id=exp).
>
> **IMPORTANT NOTICE: This repository is for archival purposes only, please refer to the maintained version on [jrl-umi3218/lipm_walking_controller](https://github.com/jrl-umi3218/lipm_walking_controller) ([documentation](https://jrl-umi3218.github.io/lipm_walking_controller/doxygen/HEAD/index.html)) for an up-to date version, and simplified installation from packages. It is not recommended to install from source, especially choreonoid and its dependencies, and we encourage you to install from the packages of the maintained repository (see up to date [installation instructions](https://jrl-umi3218.github.io/lipm_walking_controller/doxygen/HEAD/build.html))**.
>
> The remainder of this README concerns use and installation of this archival repository.

Now on the jrl-umi3218 version, we provide a simple way to install everything from packages that works out-of-the box (just tested this morning in a new docker). I'll report the updated instructions here for a quick overview, please refer to the [documentation](https://jrl-umi3218.github.io/lipm_walking_controller/doxygen/HEAD/build.html)

```
# Make sure you have required tools
sudo apt-get -qq install apt-transport-https lsb-release ca-certificates gnupg
# Add our key
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key 892EA6EE273707C6495A6FB6220D644C64666806
# Add our repository (head versions)
sudo sh -c 'echo "deb https://dl.bintray.com/gergondet/multi-contact-head $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/multi-contact.list'

# Make sure you have ROS repositories set-up
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654


# Update packages list
sudo apt-get -qq update

# Install required dependencies, Choreonoid, JVRC1 sample project and mc_rtc tools
sudo apt install libeigen3-dev doxygen libboost-all-dev libmc-rtc-dev libcopra-dev mc-openrtm jvrc-choreonoid mc-rtc-utils ros-${ROS_DISTRO}-mc-rtc-tools
```

This will install choreonoid and mc_rtc (including ROS tools and mc_openrtm) from packages.

Then to build lipm_walking:
```
git clone --recursive https://github.com/jrl-umi3218/lipm_walking_controller/
cd lipm_walking_controller && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
make -j`nproc`
sudo make install
```

Then don't forget to add `/usr/local/lib` to the `LD_LIBRARY_PATH`.

To run:
1. Start a roscore
```sh
(roscore &) # starts roscore in the background
```
2. Run the simulation
```sh
cd /usr/share/hrpsys/samples/JVRC1
./clear-omninames.sh
choreonoid sim_mc.cnoid --start-simulation
```
3. To run rviz display (and mc_rtc GUI)
```sh
roslaunch mc_rtc_ticker control_display.launch
```
4. Go to the "Walking" tab in the gui, click on "Start Standing", then "Start Walking"
5. You should now see the robot walk in both choreonoid and rviz.

I think clearly pointing newcomers towards the maintained repository would help avoid some confusion. They eventually end-up there, but usually not before having tried to install from your fork first ;)

**Comment by stephane-caron** [comment]
Sure, I've updated both the README and doc. The README didn't mention Choreonoid and already pointed to jrl-umi3218 for sources, but I added a second sentence anyway so that it's really hard to miss :wink: I guess the problem rather came from the [Build from source](https://scaron.info/doc/lipm_walking_controller/build.html) page in the documentation: I've put your disclaimer there, and moved all previous instructions for archival to a subsection clearly labeled as both "old" and "for Ubuntu 16.04".

To go further:

- You guys should increase the version number on your side. As of now it's still 1.6.0. 
- You should also update your README! It's still pretty much the same as the original.

I guess you don't care about the Docker image so much, an install-from-packages one-liner would guide visitors right away, and the usage instructions have likely changed anyway. Also, while it makes sense for me to thank you in this README, it becomes self-congratulation if you keep it on your repo :stuck_out_tongue_winking_eye: 

Hoping this helps and you never have to debug a Choreonoid/OpenRTM/OpenHRP/hrpsys installation ever again ;)
