### ISSUE TITLE
Non-horizontal foot contacts

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#58]
Dear Dr. Caron,

You stated in https://github.com/stephane-caron/lipm_walking_controller/issues/12#issuecomment-538744809:

_On a side note, if foot contacts are not horizontal, we can rectify them using the analytical projection of their contact wrench cone described in Section IV of this paper. I didn't implement this in this controller since non-horizontal foot contacts were not part of our use case._

Would you please explain which parts of the lipm_walking_controller package don't work if the foot contacts are non-horizontal?

**Comment by stephane-caron** [comment]
In the context of https://github.com/stephane-caron/lipm_walking_controller/issues/12#issuecomment-538744809 we were discussing about the [ModelPredictiveControl](https://scaron.info/doc/lipm_walking_controller/structlipm__walking_1_1_model_predictive_control.html) class used for walking pattern generation. That's the component in this controller that assumes non-coplanar but horizontal contacts.
