### ISSUE TITLE
What is the main code in the LIPM package?

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#7]
Dear Dr. Caron,
I am working with Mohamad Mahdavian and Ahmadreza Shahrokhshahi. I have studied Pymanoid package and the most recent paper of yours "Stair Climbing Stabilization of the HRP-4 Humanoid Robot using Whole-body Admittance Control". I found that some major modifications have been done in the Walking Pattern Generation and Inverse Kinematic parts of the LIPM package. In Pymanoid package, "horizontal-walking.py" is the main code for horizontal walking. However, my question is "what is the main code in the LIPM package?"

**Comment by stephane-caron** [comment]
The role of an mc_rtc controller is to initialize and update *tasks*. These tasks are in turn used to formulate and solve an IK/ID quadratic program using the [Tasks](https://github.com/jrl-umi3218/Tasks/) library, but this is done automatically so you needn't worry about it.

As in all mc_rtc controllers, there are two main functions:

- The constructor [Controller::Controller()](https://github.com/stephane-caron/lipm_walking_controller/blob/3dd1ff0aa7907f60cd805548fc7e8333abf58351/src/Controller.cpp#L29) which initializes tasks and internal objects such as the [stabilizer](https://github.com/stephane-caron/lipm_walking_controller/blob/master/src/Stabilizer.cpp) or [walking pattern generator](https://github.com/stephane-caron/lipm_walking_controller/blob/master/src/ModelPredictiveControl.cpp).
- The [Controller::run()](https://github.com/stephane-caron/lipm_walking_controller/blob/3dd1ff0aa7907f60cd805548fc7e8333abf58351/src/Controller.cpp#L527) function which is called at every control cycle. When this function returns, all tasks should have been updated properly.

Any piece of code executed in this package can be traced back to one of these two functions.
